### ISSUE TITLE
SurfaceTexture 如何生成Bitmap呢？

### ISSUE THREAD

**Issue by jp1017** [ChouRay/PlayVideo-OpenGL#3]
从简书过来的，讲的很好，有个问题，SurfaceTexture 如何生成　Bitmap　呢？

**Comment by jp1017** [comment]
用到了 TextureView, 其有个方法 getBitmap, 就用这个搞定了，谢谢咯 😄

**Comment by jp1017** [comment]
@ChouRay 谢谢，前一个链接打不开吗？

**Comment by didikeeLunaon** [comment]
@ChouRay 我试了第二个案例,保存的图片全是花屏,对视频不是很了解,希望得到每一帧的bitmap,有什么好的方法么?谢谢
